### ISSUE TITLE
"Add application" feature not working. Gives Error!

### ISSUE THREAD

**Issue by MASTERCHIEF011** [UniAuth/uniauth-backend#100]
Screen Shot of the Error
![image](https://user-images.githubusercontent.com/54094722/108470240-a9e2fa00-72af-11eb-9ee7-2cff39c88dbb.png)

**Comment by MASTERCHIEF011** [comment]
pls assign this to me

**Comment by YashKumarVerma** [comment]
what is the server response, what does the console.log tray show ?

**Comment by YashKumarVerma** [comment]
Closing due to inavtivity.
