### ISSUE TITLE
display list of users logged into application

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#106]
currently, application creators cannot see the statistics of their application or view reports.

Do the following.
- [ ] open new page by clicking on the "details" button on the application card.
- [ ] Display names of people who have logged into the application.

## Method of submission, one PR for each of the following.
- [ ] Forntend Interface to list details
- [ ] Backend logic to list user names.

**Comment by MASTERCHIEF011** [comment]
pls assign this to me

**Comment by YashKumarVerma** [comment]
@MASTERCHIEF011 please specify which one? I'll be assigning one to each

**Comment by MASTERCHIEF011** [comment]
can i do both?

**Comment by tanay13** [comment]
@YashKumarVerma Can I do the backend part if it is not assigned to anyone .

**Comment by YashKumarVerma** [comment]
> can i do both?

no.

**Comment by tanay13** [comment]
@YashKumarVerma It is showing <code>Error while creating application </code> when creating new application

**Comment by MASTERCHIEF011** [comment]
@YashKumarVerma  pls checkout out my pr for this
