### ISSUE TITLE
use partials in views to avoid code duplication

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#107]
right now, some components are being written in every view, like navbar.

To avoid this, partials can be used. Implement the same.

**Comment by MASTERCHIEF011** [comment]
assign this to me pls

**Comment by kdsinghcoder** [comment]
I can do this, I have experience with partials

**Comment by YashKumarVerma** [comment]
> assign this to me pls

you're already assigned in #106, feel free to claim other tasks once that is complete.

**Comment by YashKumarVerma** [comment]
The issue is open to be claimed.

**Comment by MASTERCHIEF011** [comment]
can you assign this to me pls.
