### ISSUE TITLE
Number of application having user access is wrong

### ISSUE THREAD

**Issue by tanay13** [UniAuth/uniauth-backend#108]
<img width="473" alt="uniauth21" src="https://user-images.githubusercontent.com/61361310/108658666-8a86df80-74f0-11eb-923f-c9fd13489a3e.PNG">
Even though I deleted both the application it is still showing the number of application having my access as 2 .

**Comment by YashKumarVerma** [comment]
alright, this is because when deleting an application, the user model still has `objectId` of the application stored.

To fix this, when deleting an application, remove ObjectId of that application from all users.

**Comment by tanay13** [comment]
I am working on this
