### ISSUE TITLE
Error in docker build

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#112]
when running `docker build -t some name .` the build shows errors. These need to be fixed.

![image](https://user-images.githubusercontent.com/14032427/108802233-d2276d00-75bd-11eb-828c-22cc30bc761d.png)

**Comment by kdsinghcoder** [comment]
@YashKumarVerma I can fix this once I am done with Partials

**Comment by MASTERCHIEF011** [comment]
pls assign this to me

**Comment by MASTERCHIEF011** [comment]
can I work on this?
