### ISSUE TITLE
add docs about running project locally

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#12]
Add docs regarding how to run the project locally.
- It needs a MongoDB server
- User should install dependencies.
- User should run the dev script. 

p.s. check package.json for more

**Comment by harshil15999** [comment]
assign to me 
Also contribution guidelines have to be given for this
If possible set up SLACK channel

**Comment by YashKumarVerma** [comment]
Thank you @harshil15999 for your interest. Since there were no instructions to run the application, i have added those. Please select any other issue. We'll be readily opening those. 

Also checkout @mexili's winter of code repo for more projects.
