### ISSUE TITLE
Integrate CodeCov Coverage Checks

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#120]
codecov can be used to effectively check the code coverage on a pull requests and commits.

Some configurations need to be done to integrate it to monitor GitHub actions and generate reports.

you can read up more about sample implementation here:https://docs.codecov.io/docs/supported-languages

https://github.com/codecov/codecov-action

## Note
- we are using JEST
- we are using github actions

**Comment by MASTERCHIEF011** [comment]
pls assign this to me
