### ISSUE TITLE
Reset password and Request password reset forms redirect to wrong url on submission!

### ISSUE THREAD

**Issue by MASTERCHIEF011** [UniAuth/uniauth-backend#127]
**Describe the bug**
On submission reset password and request password rest pages redirect to wrong url.
**To Reproduce**
1. Go to 'localhost:5000/account/login'
2. Click on 'Forgot Password'
3. Enter the email and submit

**Expected behavior**
Password Reset Request form should redirect to a server response page.
On submission reset password should redirect to a server response page which should automatically redirect to login in 5 seconds.

**Screenshots**

![image](https://user-images.githubusercontent.com/54094722/109338663-8d852580-788c-11eb-9e76-387b10327a14.png)
![image](https://user-images.githubusercontent.com/54094722/109338711-a1308c00-788c-11eb-88eb-86aeba7d7882.png)

**Comment by MASTERCHIEF011** [comment]
pls assign this to me if the issue is approved

**Comment by YashKumarVerma** [comment]
what is the meaning of `Password Reset Request form should redirect to a server response page.`?

**Comment by MASTERCHIEF011** [comment]
> what is the meaning of `Password Reset Request form should redirect to a server response page.`?

After submiting the email for password reset a page should load saying "Check you email for password reset link"
