### ISSUE TITLE
Add status badges in readme

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#14]
- Docker Image when #9 is fixed.
- Repository Details
- Code Quality Checks
- Coverage Checks

**Comment by shubhamji88** [comment]
i would like to work on this issue

**Comment by kdsinghcoder** [comment]
I will fix this after #9

**Comment by YashKumarVerma** [comment]
this issue is open to be claimed.

**Comment by MASTERCHIEF011** [comment]
pls assign this to me
