### ISSUE TITLE
Copy to clipboard button shows error on click

### ISSUE THREAD

**Issue by MASTERCHIEF011** [UniAuth/uniauth-backend#143]
**Describe the bug**
On clicking the copy to clipboard button the console shows an invalid or unexpected token error
**To Reproduce**
1. Go to 'http://localhost:5000/dashboard/dev'
2. Click on 'copy to clipboard button'
3. Open inspector tool
4. click on console tab
5. see error

**Expected behavior**
The function should copy the text to clipboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/54094722/109427932-ac192700-7a1a-11eb-87de-c695cfe823bd.png)

**Comment by YashKumarVerma** [comment]
interesting find
