### ISSUE TITLE
Error in build while starting server.

### ISSUE THREAD

**Issue by MASTERCHIEF011** [UniAuth/uniauth-backend#145]
**Describe the bug**
There is an error in building the project while starting the server

**To Reproduce**
1. Run npm run start:dev
2. See the error

**ScreenShots**
![image](https://user-images.githubusercontent.com/54094722/109443656-1d7bc880-7a61-11eb-87e3-c37f728ab0c5.png)

**Comment by YashKumarVerma** [comment]
has this been fixed in #148 ?

**Comment by MASTERCHIEF011** [comment]
> has this been fixed in #148 ?

no

**Comment by MASTERCHIEF011** [comment]
This issue has been fixed in #148
