### ISSUE TITLE
allow the user to update profile details

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#15]
The profile page currently looks like this. 

Make changes in the views (templates) and controller to allow users to update their profile details.
![image](https://user-images.githubusercontent.com/14032427/106698096-1d291280-6606-11eb-8f3f-c43574db8ccd.png)

Breakup: 25 points for frontend work, 25 points for backend work.

**Comment by tanay13** [comment]
@YashKumarVerma I want to work on this

**Comment by YashKumarVerma** [comment]
Feel free to reach out if you need help while implementing. 

Also, if you are not already part of the discord server, please find the link here: https://mexili.github.io/winter_of_code/#/

**Comment by tanay13** [comment]
@YashKumarVerma  can you tell me what is the use of <code>updateUserDto</code> in the PUT route ?

**Comment by tanay13** [comment]
@YashKumarVerma For submitting the update form we have to use <code>method-override</code> right??

**Comment by YashKumarVerma** [comment]
@tanay13 , yes you wound need to define a controller that responds to `@Post`.

You can take reference form 
- https://github.com/UniAuth/uniauth-backend/blob/master/src/account/account.controller.ts#L50-L89
or
- https://github.com/lujakob/nestjs-realworld-example-app/blob/master/src/user/user.controller.ts

**Comment by tanay13** [comment]
@YashKumarVerma for updating purpose we have to use <code>@PUT</code> right??

**Comment by YashKumarVerma** [comment]
yeah sure.
it depends on how you are implementing the profile update feature. If you are using a traditional HTML form, then it can send data only as `GET` or `POST`. However if you are sending data via fetch/ajax request, then it can be a put request.

**Comment by tanay13** [comment]
@YashKumarVerma  The user profile is getting updated but i am unable to redirect the user to the profile page from the form.
<code>
  @Put('/:id')
  @UseGuards(JwtAuthGuard)
  async update(@Param('id') id: string, @Body() updateUserDto: UpdateUserDto,@Res() res) {
    const user = await this.userService.update(id, updateUserDto);
    return res.redirect('http://localhost:5000/dashboard/profile')
  }
</code> 

This code is in user.controller.ts. Is this the right method?

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma The user profile is getting updated but i am unable to redirect the user to the profile page from the form.
> 
> ```js
>   @Put('/:id')
>   @UseGuards(JwtAuthGuard)
>   async update(@Param('id') id: string, @Body() updateUserDto: UpdateUserDto,@Res() res) {
>     const user = await this.userService.update(id, updateUserDto);
>     return res.redirect('http://localhost:5000/dashboard/profile')
>   }
> ```
> 
> This code is in user.controller.ts. Is this the right method?

Great work.

A small suggestion, it's not a good practice to redirect to absolute links (the complete URL). We could do the following.

> ```js
>   @Put('/:id')
>   @UseGuards(JwtAuthGuard)
>   async update(@Param('id') id: string, @Body() updateUserDto: UpdateUserDto,@Res() res) {
>     const user = await this.userService.update(id, updateUserDto);
>     // run function which loads the user profile. 
>   }
> ```


To load and render the user profile, you can directly call the function in the controller. For example, if the following function readers the profile of the user (https://github.com/UniAuth/uniauth-backend/blob/master/src/dashboard/dashboard.controller.ts#L41-L45), you can directly call this and show the profile.

and the above code would become

**Comment by tanay13** [comment]
@YashKumarVerma  even after doing the same the page is not being redirected 
<code>
 @Put('/:id')
  @UseGuards(JwtAuthGuard)
  async update(@Param('id') id: string, @Body() updateUserDto: UpdateUserDto,@Res() res,@Request() req) {
    const user = await this.userService.update(id, updateUserDto);
    return this.DashboardController.showProfile(req,res)
  }   
</code>

**Comment by YashKumarVerma** [comment]
@tanay13 can you send a PR for this? I'll tag it as WIP (work in progress), then I can help you out in the code as well.

**Comment by tanay13** [comment]
@YashKumarVerma sure
