### ISSUE TITLE
Show list of applications that have user's data

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#16]
Currently, the user can see only the number of applications that have got access to users data. We need to display the application along with the details that are shared with them. 

![https://i.imgur.com/ykooi3c.png](https://i.imgur.com/ykooi3c.png)

Steps:
The controller has user data. Just get details of the mongoose subdocument, and render it

**Comment by tanay13** [comment]
@YashKumarVerma I tried setting this repo on my local machine but even after npm install the dependencies are not getting installed . Can you help me out with this why is this happening ?
<img width="773" alt="npmerr" src="https://user-images.githubusercontent.com/61361310/106747053-68184980-6649-11eb-82bd-fd1f3afc71fc.PNG">

**Comment by YashKumarVerma** [comment]
@tanay13 first of all, thanks for showing interest.

Those are optional dependencies, and only `warnings`. Once the installation process completes, run `npm run start:dev`. If you face any issues, let me know.

**Comment by tanay13** [comment]
@YashKumarVerma I ran <code>npm run start:dev</code> this too but i am getting this error
<code>'nest' is not recognized as an internal or external command</code>

**Comment by YashKumarVerma** [comment]
Alright I get it.  Nest is not there in the dependencies. 


Can you please open up am issue for this?

**Comment by tanay13** [comment]
@YashKumarVerma  Ok fine . But when i cloned the original repo all the commands got executed successfully.

**Comment by tanay13** [comment]
Please assign this to me

**Comment by tanay13** [comment]
@YashKumarVerma after creating 2 applications , I should see "2 application has access to your data " right??
<img width="818" alt="appl" src="https://user-images.githubusercontent.com/61361310/106779956-82641e80-666d-11eb-9216-ae48e2a2e588.PNG">
but i am getting this


<img width="469" alt="dash" src="https://user-images.githubusercontent.com/61361310/106780158-b9d2cb00-666d-11eb-90cc-c157dc23b87c.PNG">

**Comment by YashKumarVerma** [comment]
Actually No. Developers create applications for their projects. In your cases, their names as `xyz` and `NodeJS`. 

Now note that these two applications don't have access to any user's data. 

Applications will get access to any user's data when they authorize them. i.e. User logs into them.

## How to move ahead with this
- Clone this repository. Take any example from this.
- Replace clientID, clientSecret and redirectURI depending on the application that you have created.
- Perform login.

**Comment by tanay13** [comment]
@YashKumarVerma Thanks it cleared a lot of things

**Comment by Jassi10000** [comment]
> @YashKumarVerma I tried setting this repo on my local machine but even after npm install the dependencies are not getting installed . Can you help me out with this why is this happening ?
> <img alt="npmerr" width="773" src="https://user-images.githubusercontent.com/61361310/106747053-68184980-6649-11eb-82bd-fd1f3afc71fc.PNG">

Bro actually this is a common problem due to new version of  "npm" out in the market
@tanay13   bro try this in  terminal 

# npm install -g npm@7.5.2 

### This is newest version published 3 days ago

after that do

# npm run start:dev
as asked by @YashKumarVerma 

Make sure you have running MongoDb instance running parallely in other terminal , its the best way to run an application with Nest.js used

**Comment by tanay13** [comment]
@YashKumarVerma can you assign this to me?

**Comment by tanay13** [comment]
@YashKumarVerma  How can i include clientId and client Secret provided by uniauth in my app , because in case of google auth we do something like this
<code>
passport.use(new GoogleStrategy({
    clientID:     "XYZ",
    clientSecret: "XYX",
    callbackURL: "XYZ.com",
    passReqToCallback   : true
  },
</code>

How to do this with uniauth?

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma How can i include clientId and client Secret provided by uniauth in my app , because in case of google auth we do something like this
> ` passport.use(new GoogleStrategy({ clientID: "XYZ", clientSecret: "XYX", callbackURL: "XYZ.com", passReqToCallback : true }, `
> 
> How to do this with uniauth?

Please check https://github.com/UniAuth/example-nodejs/blob/master/simple-javascript/app.js

**Comment by tanay13** [comment]
@YashKumarVerma  got it .. thanks
