### ISSUE TITLE
Enhance UI of Profile Page

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#161]
The UI of the profile page does not align with the overall theme of the application, display the user details in a nice card format, and style the edit button.

![https://i.imgur.com/wMHiVeG.png](https://i.imgur.com/wMHiVeG.png)

**Comment by Saumya008** [comment]
Hey, I would like to work on this issue.
(under GSSOC'21).

**Comment by YashKumarVerma** [comment]
requesting updates. Is there anything we can help you with?

@Saumya008
