### ISSUE TITLE
Add Dashboard link to Edit Profile Page

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#162]
The UI of the edit profile page does not align with the overall style of the application.
- the header is missing, add the header

![https://i.imgur.com/WP3bB84.png](https://i.imgur.com/WP3bB84.png)

**Comment by jnatishay78** [comment]
I would like to work on this. Please assign it to me.

**Comment by YashKumarVerma** [comment]
requesting updates. Is there anything we can help you with?

@jnatishay78
