### ISSUE TITLE
Center card in Edit Profile Page

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#163]
The UI of the edit profile page does not align with the overall style of the application.
- center the card
- improve the UI/UX of the edit card.

![https://i.imgur.com/WP3bB84.png](https://i.imgur.com/WP3bB84.png)

**Comment by jnatishay78** [comment]
I would like to work on this. Please assign it to me.

**Comment by vismitap** [comment]
I would like to work on this as a part of GSSoC!

**Comment by YashKumarVerma** [comment]
@vismitap sorry but I'm assigning issues on First come basis, feel free to pick the others

**Comment by YashKumarVerma** [comment]
requesting updates. Is there anything we can help you with?

@jnatishay78

**Comment by jnatishay78** [comment]
will u merge it now ?

**Comment by YashKumarVerma** [comment]
the PR is already merged.

**Comment by jnatishay78** [comment]
Sir is there any issue left on which I can work? 
I will be very glad to work on more issues with you.

**Comment by YashKumarVerma** [comment]
@jnatishay78 the list of open issues is available [here](https://github.com/UniAuth/uniauth-backend/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+no%3Aassignee)
