### ISSUE TITLE
Write logs to file

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#165]
The logs are being written to the console, but for them to be actually useful, we need them in a file so that they can be used later on.

Edit the logger configs to write the logs to file.

**Comment by vismitap** [comment]
I have never done this so I would like to try this issue. Please assign this to me as a part of GSSoC! ✌

**Comment by YashKumarVerma** [comment]
requesting updates. Is there anything we can help you with?

@vismitap

**Comment by vismitap** [comment]
> requesting updates. Is there anything we can help you with?
> 
> @vismitap

Will raise a PR today at night. Working on it now. ✌

**Comment by YashKumarVerma** [comment]
@vismitap requesting updates

**Comment by vismitap** [comment]
> @vismitap requesting updates

Sorry had my exams in between so could not complete this. Doing it rn!

**Comment by YashKumarVerma** [comment]
These reference might help you start off:
- https://stackoverflow.com/questions/58121749/nestjs-logging-into-file-database-etc-using-either-default-logger-or-npm-like
- https://github.com/nestjs/nest/issues/1299

**Comment by aniketbiswas21** [comment]
@YashKumarVerma Is this issue still being worked upon? If not, can I work on this?

**Comment by YashKumarVerma** [comment]
Please do
