### ISSUE TITLE
Fix method to check user participation in applications

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#166]
The method which is used to get the list of applications that have access to user data is located in `application.service.ts`, the method name is `findAllByParticipant(user:User`

![https://i.imgur.com/Q55BFfi.png](https://i.imgur.com/Q55BFfi.png)

This directly compares the object therefore it is not working.
```js

  async findAllByParticipant(user: User): Promise<Array<Application>> {
    const item = await this.applicationModel.find({ participants: user });
    return item;
  }
```

Fix:
check if he user exists in the participants array and return the applications in which the user is there.

ref:
https://stackoverflow.com/questions/41404599/mongoose-check-if-value-exists-in-an-array-of-objects/41404781

**Comment by aniketbiswas21** [comment]
I would like to work on this.
