### ISSUE TITLE
Fix placement of delete button

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#167]
all of them should be in the same line, and the heading should not cover 100% of with width

![https://i.imgur.com/tR15sMv.png](https://i.imgur.com/tR15sMv.png)

**Comment by Saumya008** [comment]
I would like to work on this. Please assign it to me.

**Comment by YashKumarVerma** [comment]
requesting updates. Is there anything we can help you with?

@Saumya008
