### ISSUE TITLE
Remove excess space in input areas

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#168]
remove the excess space towards the left of each input box

![https://i.imgur.com/ApO3UVd.png](https://i.imgur.com/ApO3UVd.png)

**Comment by jnatishay78** [comment]
I would like to work on this. Please assign it to me.

**Comment by vismitap** [comment]
I would like to work on this as a part of GSSoC'21. Please assign this to me! 😇

**Comment by YashKumarVerma** [comment]
@jnatishay78 i'm assigning you #162 , and giving this one to @vismitap

**Comment by YashKumarVerma** [comment]
requesting updates. Is there anything we can help you with? 

@vismitap

**Comment by vismitap** [comment]
> requesting updates. Is there anything we can help you with?
> 
> @vismitap

Working on it rn. Will make a PR by today night or tomorrow. If any doubts, I will ask you on discord. Thanks✌

**Comment by vismitap** [comment]
![image](https://user-images.githubusercontent.com/47056243/111962963-00df2780-8b19-11eb-867e-7302facd66f2.png)
I am getting this error. Tried to contact on discord but don't have permission to post image there.

**Comment by YashKumarVerma** [comment]
> ![image](https://user-images.githubusercontent.com/47056243/111962963-00df2780-8b19-11eb-867e-7302facd66f2.png)
> I am getting this error. Tried to contact on discord but don't have permission to post image there.

this issue is fixed in #179, it's because the description length was minimum 15 characters. this condition is now removed. 

so you can update your fork, or just remove one line (check 179 to know which), or have a description more than 15 characters long
