### ISSUE TITLE
Add logo to navbar in application details

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#169]
![https://i.imgur.com/oevkpk8.png](https://i.imgur.com/oevkpk8.png)
- Add application logo in navbar

**Comment by Saumya008** [comment]
Hi,
I would like to contribute to this project as GSSOC'21 participant. Please assign this issue to me.
Thanks.

**Comment by YashKumarVerma** [comment]
@Saumya008 you're already assigned two issues, lets fix those before assigning more 😄

**Comment by Harshpatel2222** [comment]
@YashKumarVerma  I would like to fix this can you assign this issue to me?

**Comment by EANimesha** [comment]
I'm a GSSOC'21 participant. can I contribute to this issue?

**Comment by YashKumarVerma** [comment]
> I'm a GSSOC'21 participant. can I contribute to this issue?

we're assigning issues first come first serve, please check out other repos [here](https://github.com/UniAuth?type=source) for more issues

**Comment by YashKumarVerma** [comment]
requesting updates @Harshpatel2222 . Is there anything we can help you with?

**Comment by YashKumarVerma** [comment]
@EANimesha @Saumya008 this issue is free right now. Any one of you wish to work on this ?

**Comment by Saumya008** [comment]
yeah sure please assign it to me.
