### ISSUE TITLE
JS Error while creating new applicaiton

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#17]
While creating a new application in `/dashboard/dev`, there is a js error triggered which is :

![https://i.imgur.com/7CMojyO.png](https://i.imgur.com/7CMojyO.png)

This needs to be fixed.

**Comment by kdsinghcoder** [comment]
@YashKumarVerma  assign this to me

**Comment by YashKumarVerma** [comment]
also @kdsinghcoder , if you have not joined our discord server, please do. find the link on https://mexili.github.io/winter_of_code/#/
