### ISSUE TITLE
Create UI for My Data Page

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#172]
currently, the page looks like this:

![https://i.imgur.com/HPotqg7.png](https://i.imgur.com/HPotqg7.png).

Show each application in a card format.

**Comment by sk1122** [comment]
I can work on it @YashKumarVerma

**Comment by YashKumarVerma** [comment]
requesting updates. Is there anything we can help you with?

**Comment by sk1122** [comment]
@YashKumarVerma I am on it, i will let you know if i need any help

**Comment by sk1122** [comment]
I have created a Sample Design.
See if it is right
![Uniauth](https://user-images.githubusercontent.com/40713709/112147339-986c7500-8c02-11eb-93c9-c00dfbd32a7f.png)

**Comment by YashKumarVerma** [comment]
> I have created a Sample Design.
> See if it is right
> ![Uniauth](https://user-images.githubusercontent.com/40713709/112147339-986c7500-8c02-11eb-93c9-c00dfbd32a7f.png)

Looks dope ! Good work !

**Comment by sk1122** [comment]
@YashKumarVerma Should I commit?

**Comment by YashKumarVerma** [comment]
sure, send a pr @sk1122
