### ISSUE TITLE
create docker-compose to launch entire stack

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#19]
docker-compose can be used to launch the entire stack at once using a single command.

Create a docker-compose file to launch a mongodb server and uniauth-backend image.

**Comment by DarthBenro008** [comment]
Hey, 
I would like to work on this 😄

**Comment by Jassi10000** [comment]
I want to try this one out , assign me this under MWOC  @YashKumarVerma 
One more thing , I hope it doesn't require a Linux machine

**Comment by YashKumarVerma** [comment]
No it does not require.

**Comment by Jassi10000** [comment]
@YashKumarVerma sir I have tried to run the docker command after making changes, and its again and again prompting me to install some WSL and restart , without it , the command is not running

**Comment by MASTERCHIEF011** [comment]
pls assign this to me
