### ISSUE TITLE
Add `copy` feature in the application details

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#20]
The current interface does not allow the user to copy the text directly. This is a heavily demanded feature. This can be done by adding a small copy button in the text field itself, towards the right side.

![https://i.imgur.com/eKH2Ze5.png](https://i.imgur.com/eKH2Ze5.png)

The copy button can be something like :
![https://i.imgur.com/j39qbW0.png](https://i.imgur.com/j39qbW0.png)

**Comment by kdsinghcoder** [comment]
@YashKumarVerma  let me do this !!

**Comment by YashKumarVerma** [comment]
Sure @kdsinghcoder !
