### ISSUE TITLE
Registeration Number not getting accepted 

### ISSUE THREAD

**Issue by Jassi10000** [UniAuth/uniauth-backend#21]
These are pics of  what am getting at localhost:5000 after registering my details 

1.This first image is when localhost:5000 runs in normal tab 
![image](https://user-images.githubusercontent.com/64856348/106723077-bf5bf100-662c-11eb-84e9-a1e633abda51.png)

2. The second image is of localhost:5000 in  Incognito mode as due to " 400 " , I thought maybe its due to cookies or cache  , but then also the result is same
![image](https://user-images.githubusercontent.com/64856348/106725819-c6d0c980-662f-11eb-9e74-22656dc26972.png)

I don't why registeration number is not being accepted ,as it was mentioned in Readme file to include any random Registeration Number 

I have also checked the URL , it's same as given in the Readme
here's the snapshot
![image](https://user-images.githubusercontent.com/64856348/106727865-e5d05b00-6631-11eb-9cc6-b730a92d5e4d.png)

**Comment by YashKumarVerma** [comment]
alright, the thing is, to demonstrate that there can be variations in input fields, I have validations in the system.

Use any registration number of the format : [2 digit year][3 character code][4 digit number]
Something like 19BCE2669, 19MIT0001, 20BTC0010 etc.

This is the way registration numbers are there in my college, so I followed same.

**Comment by Jassi10000** [comment]
@YashKumarVerma Ohh !! that's why I got this

No issues , I'll just try with these examples 
btw can I make this change in the readme as well so that other peeps who are first time visitors like me don't face this  same problem
May be I can do a contribution in this way

**Comment by YashKumarVerma** [comment]
Sure @Jassi10000, please send a PR to update the docs.

**Comment by Jassi10000** [comment]
Thanks @YashKumarVerma for this opportunity , I'll do it right away
