### ISSUE TITLE
nest is not there in the dependencies

### ISSUE THREAD

**Issue by tanay13** [UniAuth/uniauth-backend#24]
After executing <code>npm run start:dev </code> following error occurs .
<img width="564" alt="nest" src="https://user-images.githubusercontent.com/61361310/106750769-48cfeb00-664e-11eb-86c8-6f0fa8e5dedd.PNG">

**Comment by YashKumarVerma** [comment]
can you fix this and send a PR @tanay13 ?

**Comment by YashKumarVerma** [comment]
@tanay13 I launched a clean environment inside a container and did not face any issue as mentioned.

**Comment by tanay13** [comment]
@YashKumarVerma I don't know why but i am still getting that error

**Comment by tanay13** [comment]
@YashKumarVerma  It worked now i cloned it again and now its working fine

**Comment by YashKumarVerma** [comment]
Cool. Looks like it was some local conflict. Closing for now.
If you face any issues, feel free to ping again.
