### ISSUE TITLE
Add delete application feature to dashboard

### ISSUE THREAD

**Issue by kdsinghcoder** [UniAuth/uniauth-backend#32]
![image](https://user-images.githubusercontent.com/50829119/106792891-bd218300-667c-11eb-87a1-79c53d2768f8.png)

add a red color delete or remove icon on the right side of the application card so as to remove or delete that application.

![image](https://user-images.githubusercontent.com/50829119/106793434-7aac7600-667d-11eb-96bb-a2affcdd4ecb.png)

**Comment by Jassi10000** [comment]
@YashKumarVerma Can you please assign me this , I want to give it a nice try

**Comment by YashKumarVerma** [comment]
As far as I know, @kdsinghcoder  is working on it.

**Comment by Jassi10000** [comment]
@kdsinghcoder  Actually I think then the English he wrote is wrong as he has written 
" Add a delete of remove Button on My application Card  "

which clearly says that he's expecting someone to work on the issue ,
Plss can you ask @kdsinghcoder  to correct the English of issue heading so that someone else also doesn't gets confused

**Comment by kdsinghcoder** [comment]
@YashKumarVerma  assign this to @Jassi10000 veer.

I was trying this but faced some issues.

**Comment by Jassi10000** [comment]
@YashKumarVerma The delete button will delete the application user has created , right?

**Comment by YashKumarVerma** [comment]
this would reside in the `application` module (folder is `src/application`).

You'd need to create a controller in `application.controller.ts` which calls a function from `application.service.ts`

**Comment by YashKumarVerma** [comment]
@Jassi10000 can you send a PR with the work that you have done till now? 
This way we can help you better.

**Comment by MASTERCHIEF011** [comment]
can u pls assign this to me
