### ISSUE TITLE
Regarding the auto-refresh

### ISSUE THREAD

**Issue by Jassi10000** [UniAuth/uniauth-backend#34]
![image](https://user-images.githubusercontent.com/64856348/107007314-5d2ff700-67b8-11eb-829b-8f7944bb8392.png)

After I click on " Create Application " , it's not auto - refreshing 

I have to manually do that  to get this :

![image](https://user-images.githubusercontent.com/64856348/107007423-86e91e00-67b8-11eb-9c74-1bc6305423d7.png)

**Comment by YashKumarVerma** [comment]
Thank you for raising this issue, this is already listed under #17, therefore closing.
