### ISSUE TITLE
Add View password feature to the Input tag 

### ISSUE THREAD

**Issue by kdsinghcoder** [UniAuth/uniauth-backend#37]
![image](https://user-images.githubusercontent.com/50829119/107371476-5253ca00-6b0a-11eb-9b00-8efc045cf696.png)

![image](https://user-images.githubusercontent.com/50829119/107371510-5e3f8c00-6b0a-11eb-9756-096dc8cc3aca.png)

**Comment by kdsinghcoder** [comment]
@YashKumarVerma  assign this to me if this issue is valid.

**Comment by YashKumarVerma** [comment]
since this issue is fixed in a different PR, please send a PR updating the readme with this feature.
