### ISSUE TITLE
tests: write tests for dashboard controller

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#40]
tests files are named as `*.spec.ts` files.

Checkout such files for controllers for more reference.

**Comment by tanay13** [comment]
@YashKumarVerma please assign this to me

**Comment by YashKumarVerma** [comment]
I have set up tests for user controller, will merge it soon. You can take references from there .

**Comment by YashKumarVerma** [comment]
@tanay13 please check #39 for reference. I have written tests for user controller.

**Comment by tanay13** [comment]
<img width="372" alt="routeuser" src="https://user-images.githubusercontent.com/61361310/108032154-09df6380-7058-11eb-929a-2a9e5d692d71.PNG">
@YashKumarVerma  How the edit functionality is still working when it has been commented out ?

**Comment by tanay13** [comment]
``` js
  describe('.create()', () => {
    it('should be defined', () => {
      expect(controller.create).toBeDefined();
    });
  });
```
In this ( and all other functions as well ) why we aren't checking whether the user has been created or not ?

**Comment by YashKumarVerma** [comment]
> ```js
>   describe('.create()', () => {
>     it('should be defined', () => {
>       expect(controller.create).toBeDefined();
>     });
>   });
> ```
> 
> In this ( and all other functions as well ) why we aren't checking whether the user has been created or not ?
> Should i also proceed like this?

that can (and should) be done. I have just setup the dependencies and overall framework to write tests. The remaining would be done by the community.

**Comment by tanay13** [comment]
@YashKumarVerma  i had one doubt 
```js
            login: jest.fn(() => true),
            create: jest.fn(() => true),
            pushApplicationIntoUserParticipantList: jest.fn(() => true),
            findAll: jest.fn(() => true),
            findOneById: jest.fn(() => true),
            update: jest.fn(() => true),
            remove: jest.fn(() => true),
```
instead of returning true for all mock functions we have to write the actual function inside the jest.fn() right??
