### ISSUE TITLE
Setup E-Mail Module

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#43]
To successfully complete this task, do the following.

1. create a new module named mailing (see nest modules)
2. use any mailing service which provides reasonable resources for free.
3. add the following methods in the mailer service.
    - function to send email, must accept `toEmail` and `emailBody`.

**Comment by tanay13** [comment]
@YashKumarVerma  please assign this to me

**Comment by MASTERCHIEF011** [comment]
I was implementing the reset password issue and have integrated this into the same
