### ISSUE TITLE
Implement password reset

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#44]
when #43 is done, we need to use that module to send emails when the user requests to reset their password.

This MUST:
- send email to user's verified email 
- the email must contain a uniquely generated password reset link.
- the above-generated link should be saved in `user` mongoose model. 
- the password reset link must expire after a said time (jwt's can be used for this  or timestamp can be saved for this or any other approach that you feel is reliable)
- write a controller to accept the password reset link and overwrite the users password.
- destroy the reset link from the database.

Feel free to ask for help/ guidance when implementing this.

**Comment by MASTERCHIEF011** [comment]
pls assign this to me
