### ISSUE TITLE
Allow forks to customize application from single file

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#45]
When users fork UniAuth to implement the system for their organization, currently they need to edit the names of the application in numerous files which is a tedious and boring process. 

To fix the above problem, we can load all such details (application name, description, etc) from a particular file (configs are best for this, checkout the config folder and how the `config.get` method works in the codebase). 

These can be then passed into the `views` from the `controllers` to display at various places.

**Comment by MASTERCHIEF011** [comment]
pls assign this to me

**Comment by kdsinghcoder** [comment]
@YashKumarVerma  assign this to me

**Comment by YashKumarVerma** [comment]
Since @MASTERCHIEF011 is assigned issues in the flask-middleware, assigning this to @kdsinghcoder

**Comment by YashKumarVerma** [comment]
this issue is open to be assigned.

**Comment by kdsinghcoder** [comment]
@YashKumarVerma I am working on this.

**Comment by YashKumarVerma** [comment]
open to claim and work.
