### ISSUE TITLE
Setup pre-commit hook to lint and format

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#63]
Since the number of contributions is increasing by the day, some problems are starting to arise. 

The reason is that different people have different writing styles and this is harmful to the project lifecycle.

Read up this post: https://elijahmanor.com/blog/npm-precommit-scripts

Attach the following commands:
- yarn format
- yarn lint

**Comment by MASTERCHIEF011** [comment]
pls assign this to me.

**Comment by kdsinghcoder** [comment]
@YashKumarVerma  assign this to me
