### ISSUE TITLE
tests: write tests for dashboard service

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#67]
We have already set up tests for user service.

Take it as a reference, and write tests for dashboard service.

Also, please attach screenshots of tests passing when sending PRs.

**Comment by tanay13** [comment]
@YashKumarVerma  Please assign this to me

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma Please assign this to me

Sure @tanay13.
Also for further work, don't wait for me to assign you. Simply comment that you're working on it, tag me, and I'll assign you when I come online.

**Comment by tanay13** [comment]
@YashKumarVerma unlike user service, dashboard service is just returning simple text as we are not using those anywhere so what should I write for testing?

**Comment by YashKumarVerma** [comment]
Just ensure that it is defined.
