### ISSUE TITLE
tests: write tests for auth service

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#68]
We have already set up tests for user service.

Take it as a reference, and write tests for auth service.

Also, please attach screenshots of tests passing when sending PRs.

**Comment by tanay13** [comment]
@YashKumarVerma I am working on this

**Comment by tanay13** [comment]
@YashKumarVerma Wasn't this assigned to me??

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma Wasn't this assigned to me??

really sorry @tanay13  I did not check while merging as the PR was apt to be merged. 

@MASTERCHIEF011 please avoid sending PR when it is assigned to someone else.

There are few unused variables in this file, could you fix those?
![image](https://user-images.githubusercontent.com/14032427/108402411-7b2f3a00-7243-11eb-9efa-069ed308e614.png)

yellow lines are variables not being used.

**Comment by tanay13** [comment]
@YashKumarVerma No problem
