### ISSUE TITLE
Migrate user operation to Dashboard

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#69]
Since profile update comes under the dashboard, move it to the dashboard.controller.ts file.

The function in dashboard.controller.ts should use the user service.

https://github.com/UniAuth/uniauth-backend/blob/591c0553288e45dfd46cacd5f1d622c68f281560/src/user/user.controller.ts#L69-L91

**Comment by kdsinghcoder** [comment]
Assign this to me @YashKumarVerma

**Comment by MASTERCHIEF011** [comment]
pls assign this to me
