### ISSUE TITLE
Remove unused controller functions from user module

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#71]
Ideally, the user module should provide only `service` to operate on **users**, and the **dashboard** module should perform operations using that service.

Remove the methods from user.controller.ts

**Comment by kdsinghcoder** [comment]
@YashKumarVerma  if it's not assigned I can do this.

**Comment by YashKumarVerma** [comment]
Sorry but @fleventy-5 is currently assigned on this.

**Comment by kdsinghcoder** [comment]
@YashKumarVerma if it's free, Assign this to me.
