### ISSUE TITLE
Server crashing on loading landing page!

### ISSUE THREAD

**Issue by MASTERCHIEF011** [UniAuth/uniauth-backend#72]

**Comment by YashKumarVerma** [comment]
please add a description of the problem, the errors that you see.

**Comment by YashKumarVerma** [comment]
![image](https://user-images.githubusercontent.com/14032427/108302585-4501a400-71ca-11eb-9a8d-ee55021a8e25.png)

I faced no issues in running the server. 
Could you confirm @MASTERCHIEF011

**Comment by MASTERCHIEF011** [comment]
Try visiting the landing page:
Here is a snapshot:
![image](https://user-images.githubusercontent.com/54094722/108305352-cb6cb480-71cf-11eb-83ef-6ff0425482c0.png)

**Comment by YashKumarVerma** [comment]
@tanay13 @Jassi10000 
is the current master branch working for you? Are you also facing issues in running?

From what I can see, @MASTERCHIEF011 and @kdsinghcoder are running on windows systems and facing issues. I am running on linux based system and not facing.

**Comment by Jassi10000** [comment]
@YashKumarVerma 
![app1](https://user-images.githubusercontent.com/64856348/108487691-8aef6280-72c5-11eb-8a25-39a999839e03.PNG)

Its' working fine in windows too
Maybe @MASTERCHIEF011 has not started the mongoDb instance 
@MASTERCHIEF011 bro just restart the machine once and run the application and mongoDb instance from fresh , and you are good to go 
Actually it happened with me also before , so nothing to worry , just do these things

**Comment by tanay13** [comment]
@YashKumarVerma Its working fine for me as well, but when I merged the original repo master branch with my forked branch I saw that the update controller has been commented out but still I am able to update my profile . How is this happening?

**Comment by tanay13** [comment]
@YashKumarVerma The landing page loaded when i ran it using my forked repo but when i ran the server from the original repo its not working .

**Comment by MASTERCHIEF011** [comment]
@Jassi10000 Bro I think its not the mongo db instance. Can you please fork the UniAuth master branch again and run the server. And pls  visit the landing page to see if the server crashes or not.

**Comment by YashKumarVerma** [comment]
> @YashKumarVerma The landing page loaded when i ran it using my forked repo but when i ran the server from the original repo its not working .

I have also experienced this.

Also, this has nothing to do with mongodb.

**Comment by tanay13** [comment]
@YashKumarVerma Any idea why this is  happening ?

**Comment by MASTERCHIEF011** [comment]
@tanay13 for now you can configure the directory as 
app.useStaticAssets(join(__dirname, '..', '../public'));
app.setBaseViewsDir(join(__dirname, '..', '../views'));
instead of 
app.useStaticAssets(join(__dirname, '..', 'public'));
app.setBaseViewsDir(join(__dirname, '..', 'views'));

**Comment by YashKumarVerma** [comment]
I will investigate more into this, but **as of now** the PR sent by @MASTERCHIEF011 fixes this.

**Comment by tanay13** [comment]
> @YashKumarVerma Its working fine for me as well, but when I merged the original repo master branch with my forked branch I saw that the update controller has been commented out but still I am able to update my profile . How is this happening?

@YashKumarVerma What about the update function ?

**Comment by YashKumarVerma** [comment]
> > @YashKumarVerma Its working fine for me as well, but when I merged the original repo master branch with my forked branch I saw that the update controller has been commented out but still I am able to update my profile . How is this happening?
> 
> @YashKumarVerma What about the update function ?

I am not sure why this is happening. Could you delete ur fork and make a fresh one ?
