### ISSUE TITLE
Application Layout broken

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#86]
All applications should have a different card.
![image](https://user-images.githubusercontent.com/14032427/108302762-a6c20e00-71ca-11eb-8cef-c64a15547961.png)
![image](https://user-images.githubusercontent.com/14032427/108302780-b2add000-71ca-11eb-9690-17d673e92163.png)

**Comment by kdsinghcoder** [comment]
@YashKumarVerma  assign this to me.

**Comment by YashKumarVerma** [comment]
This issue is open to be claimed.
