### ISSUE TITLE
dockerize application

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#9]
Write a docker file to create a container image of the UniAuth Backend. 

Make sure to
- Document the environment variables

**Comment by shubhamji88** [comment]
i would like to work on this issue

**Comment by kdsinghcoder** [comment]
@YashKumarVerma  assign this to me if you can

**Comment by YashKumarVerma** [comment]
@shubhamji88 are you working on it? Can you share your approach or work till now ?

**Comment by shubhamji88** [comment]
assign it to karan, i am having some difficulties..

**Comment by YashKumarVerma** [comment]
> assign it to karan, i am having some difficulties..

no problem. 
if you are interested in a similar task, you can try out #19
