### ISSUE TITLE
Fix user.service unit tests

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#96]
https://github.com/UniAuth/uniauth-backend/blob/1ba38d80f4100679c6c129c51c392ca3490e3d79/src/user/user.service.spec.ts#L12-L18

![image](https://user-images.githubusercontent.com/14032427/108405527-2ee5f900-7247-11eb-96dc-15885db8cbd8.png)

**Comment by tanay13** [comment]
@YashKumarVerma I am working on this
