### ISSUE TITLE
Project CleanUp alert

### ISSUE THREAD

**Issue by YashKumarVerma** [UniAuth/uniauth-backend#97]
On the following timestamp, we would unassign developers from few issues and close pull requests.

# Feb 22 (Monday), 10:00 AM IST 💀 

## Reasons:
- To eliminate the deadlock as some issues are assigned and not showing any progress for large periods of time.
- To allow other developers try those issues.
- To ease merging / reviewing pull requests.

## Which issues will be reassigned?
- Only selected issues will be reassigned. 
- The following conditions should be met to reassign an issue
	- the issue is opened more than 48 hours (2 days) before.
	- the issue is assigned more than 48 hours (2 days) before.
	- the assigned developer has not opened a PR in the last 24 hours(1 day) for the issue.
	- the PR is not updated in the last 24 hours after changes were requested / review.

## Which Pull Requests would be closed?
- Only those pull requests would be closed which have not been updated in the last 24 hours after review.

## FAQ
- I was assigned issue X, can i get assigned again?
    - Yes, If the issue X was unassigned from you, you can get it assigned again by commenting on the issue and tagging me (@YashKumarVerma)
- My pull request was closed, can I send again?
    - Yes, if the issue is assigned to you again, you can send a PR.

**Comment by YashKumarVerma** [comment]
Pinging for visibility.

@MASTERCHIEF011 @tanay13 @kdsinghcoder @Jassi10000

**Comment by Jassi10000** [comment]
> Pinging for visibility.
> 
> @MASTERCHIEF011 @tanay13 @kdsinghcoder @Jassi10000
> 
> Feel free to ask any doubt if you have.

Actually sir, am new to typescript , that's why getting some problems along the way , not able to relate how to relate the problem

**Comment by YashKumarVerma** [comment]
> > Pinging for visibility.
> > @MASTERCHIEF011 @tanay13 @kdsinghcoder @Jassi10000
> > Feel free to ask any doubt if you have.
> 
> Actually sir, am new to typescript , that's why getting some problems along the way , not able to relate how to relate the problem

No issues, if there's some issue you are working on, open a pr for it (it's called a WIP : work in progress PR) and we can help you fix the issue then.

**Comment by Jassi10000** [comment]
Sure I will do that
